### PR TITLE
Chinese simplified

### PR DESCRIPTION
**Pull request by lpjjj1222**
Solved issue https://github.com/wordplaydev/wordplay/issues/419

### CODE REVIEW

**Review by amyjko — CHANGES_REQUESTED** [review]
There are several conflicts in these files; resolve them and then this can be merged.

**Review by amyjko — CHANGES_REQUESTED** [review]
* Please run `npm run locales` before submitting localization changes; this branch has several localization formatting errors that need to be resolved.
* Many of the templates with parameters (e.g., the `$1` in `the number is $1`) were removed in the Chinese translation. Restore those parameters so that information isn't lost in the descriptions.

**Review by benjaminmeow — COMMENTED** [review]
They locale file as been updated with new translations and fixed ones that were out of date!

**Review by benjaminmeow — COMMENTED** [review]
Updating the zh-CN.json with new transaltions and updating old outdated ones. Notice that there is a dummy tutorial file because we are stil debugging it.

**Review by amyjko — CHANGES_REQUESTED** [review]
This looks almost ready, but there appear to be some syntax errors in the locales. For example, throughout, the syntax `$[...]` is used, as in `$[phrase]`, when it you probably mean `$phrase`. `[]` are used in the locale syntax as a conditional.

There are also other syntax errors. For example, `Source > doc` has a code example that is missing the code example escape characters, which is causing the app to crash when creating a new project. 

Remember, in addition to running `npm run locale` to find errors, you want to actually test these translations too, in the live application, to make sure they don't have defects and appear correctly in the interface. Per the documentation, hover over the JSON property keys to see documentation on where they appear in the interface, or what situation they appear in.

**Pull request closed without merging**
