### PR TITLE
Basketball Star project on new branch

### PR DESCRIPTION
**Pull request by vTempo**

### CODE REVIEW

**Comment by amyjko** [comment]
It could be a defect in the test, or in the program analysis engine. I'll investigate and report back.

**Comment by amyjko** [comment]
I think I found the cause (infinite recursion in a conflict analysis caused by a defect). I should be able to fix it tonight.

**Comment by vTempo** [comment]
Thank you very much! Should I open an issue about it so maybe someone in verification can look into it as well?

**Comment by amyjko** [comment]
Nope, I know the cause, I just need time to fix it. (Meetings now until 5, then I have some time).

**Comment by amyjko** [comment]
Found a few minutes to fix it. The dependency analysis bug was masking a few conflicts in your program; you can see the changes I made to it to resolve them.

**Pull request merged**
