### PR TITLE
Create Snail.wp

### PR DESCRIPTION
**Pull request by selenayu000**

### CODE REVIEW

**Review by amyjko — CHANGES_REQUESTED** [review]
What a cute little snail! I wonder if we could make this a bit more complex? It seems a bit simple relative to the tutorial examples. Are there some forms of interactivity you could add to it, that might help show some more complex design patterns? For example, maybe the snail's job is to get something, and maybe the snail gets slower the closer it gets to it, because it's a snail?

**Comment by amyjko** [comment]
@selenayu000 Any thoughts?

**Comment by selenayu000** [comment]
I like the idea of the snail getting slower the closer it gets, I can try my best to attempt

**Comment by amyjko** [comment]
@selenayu000 Send me questions if you get stuck!

**Comment by amyjko** [comment]
@selenayu000, any updates on this example?

**Comment by amyjko** [comment]
Any updates on this example @selenayu000? I haven't see n any replies on this for more than a month.

**Comment by amyjko** [comment]
Deleting this PR and branch, since there's no reply from @selenayu000.

**Pull request closed without merging**
