### PR TITLE
Add WCAG AxeBuilder Tests for Subtitles on Homepage

### PR DESCRIPTION
**Pull request by meepsterleapster**
This change list is to use AxeBuilder to detect WCAG violations on subtitles on the Wordplay homepage.

This change required the inclusion of the AxeBuilder dependency in order to run. This was done manually by running the following command: npm install @axe-core/playwright

For example: To run this test individually on a Chrome Browser:
 npx playwright test tests/home.WCAG2.AxeBuilder.test.ts --project="Google Chrome" 

If a violation is detected, look at the   "failureSummary", "description",  and "help" for each violation to determine the changes needed to fix.

Example of failure:
image

### CODE REVIEW

**Comment by meepsterleapster** [comment]
The check that is unsuccessful is the test I just implemented

**Review by amyjko — CHANGES_REQUESTED** [review]
Thanks for the draft PR @meepsterleapster! This looks like a great start. A few thoughts:

* Good tests do their best to cleanly communicate feedback about their failures. I recommend doing a bit of work to pull out the violations and format them so they are more readable, so anyone that violates a test can quickly see what broke.

* There are many AXE warnings that are just possible failures, and not categorically wrong. I see you're currently filtering for level A and AA compliance issues. Does Axe throw any false positive for these compliance violations? And why not include AAA violations? Let's aim really high on accessibility!

* There's an interesting process question about what to do with PRs that add tests that are failing; by merging them in with failures, they'll inherently break all future PRs, because there will always be failing tests. I'm wondering if we need to add to the set of responsibilities for the verification role that you need to also fix the defects as part of the PR? (There is an issue on contrast, #371, that would likely resolve this).

**Comment by meepsterleapster** [comment]
> * Good tests do their best to cleanly communicate feedback about their failures. I recommend doing a bit of work to pull out the violations and format them so they are more readable, so anyone that violates a test can quickly see what broke.
> * There are many AXE warnings that are just possible failures, and not categorically wrong. I see you're currently filtering for level A and AA compliance issues. Does Axe throw any false positive for these compliance violations? And why not include AAA violations? Let's aim really high on accessibility!

**Comment by amyjko** [comment]
Thanks @meepsterleapster. Do you want to work on resolving the test failures? We'll want to make sure those tests are passing before we merge this.

**Comment by meepsterleapster** [comment]
I can look at the issue a bit, but with my knowledge almost exclusively limited to stuff around testing and playwright, I am unsure if I will be able to gain the required knowledge and implement a fix by the quarter's end

**Comment by amyjko** [comment]
@meepsterleapster This is about third bullet in the comment above: should people writing tests be responsible for fixing defects they find? Should we merge failing tests without first fixing them? How can someone else know there's a defect to fix unless the test is merged? 

Our current verification guidelines have the answer:

https://github.com/wordplaydev/wordplay/wiki/design#propose-designs

I can help you understand the fixes necessary, and we'll make as much progress as you have time for. If you don't finish it, this PR should have sufficient context for someone else to finish the work, get the tests to pass, and then merge the new test.

**Comment by meepsterleapster** [comment]
The test keeps timing out on Mobile Safari, on different pages and only on the Github testing side, local run works. I suspect the emulator is just very very slow.
  
  Error screenshots:
image
image

**Comment by amyjko** [comment]
@meepsterleapster I had the exact same issue on the `Learn` page after resolving some of the tests. It is possible that it's slowness, but none of my investigations turned anything up, and increasing the timeouts didn't help. I'm a bit stumped on why it would only be failing on GitHub. One possibility is networking limitations, though I looked at network requests, and none of them were hanging as unresolved after the timeout, so that doesn't seem likely. You can investigate the traces that GitHub generates to inspect further.

**Comment by amyjko** [comment]
@meepsterleapster One way forward on this: remove Mobile Safari from the Playwright config, and file an issue on Mobile Safari for us to resolve later. That would at least unblock this PR.

**Comment by meepsterleapster** [comment]
Followed your advice and disabled the Mobile Safari test. Opened [Issue #408 ](https://github.com/wordplaydev/wordplay/issues/408) for future investigation.

**Comment by meepsterleapster** [comment]
rebase my private branch, and followed your advice from last Wednesday's meeting.

**Review by amyjko — COMMENTED** [review]
Nearly ready to go! There were just some TypeScript errors in the test that needed to be resolved.

**Review by amyjko — APPROVED** [review]
All ready to go, nice work researching Axe!

**Comment by amyjko** [comment]
All merged, congrats @meepsterleapster!

**Pull request merged**
