### PR TITLE
es-MX tutorial

### PR DESCRIPTION
**Pull request by cmdharo**
- Finished complete draft of the es-MX tutorial
   - All words/phrases should have been translated, but further review for clarity, mistranslations, and consistency is highly recommended 
- Made minor edits/updates to the es-MX JSON file

### CODE REVIEW

**Review by amyjko — CHANGES_REQUESTED** [review]
This is looking great! A few things I noticed will skimming through the translation:

* Some parts of the tutorial are still in English. Much of `Boolean` for example, is still in English
* Most of the programs are still in English. Text and names should all be in Spanish, not English. For example, "Phrase" should be "Frase", and text literals should be Spanish words, not English words.
* Many of the scene titles and subtitles are still in English.

I think our goal for this should be to translate everything, even if the first draft isn't as polished as we like.

**Comment by cmdharo** [comment]
Sounds good! I just went and translated all the programs into Spanish. I'll do the titles, subtitles, and any other parts not yet translated.

**Comment by amyjko** [comment]
Sounds good! I look forward to the new commits.

**Comment by amyjko** [comment]
@cmdharo Looks like there a few conflicts here to resolve after some redesigns. Can you resolve and then I'll merge?

**Comment by cmdharo** [comment]
@amyjko Oops, yes, I didn't mean to commit yet. I'll fix those right away!

**Comment by amyjko** [comment]
Looks like there's still one conflict to resolve.

**Pull request closed without merging**
