### PR TITLE
Completed es-MX.json for beta 

### PR DESCRIPTION
**Pull request by cmdharo**
-Fixed any locale issues in the bassis section of es-MX
-Completed all missing strings
-Fixed some formatting issues

### CODE REVIEW

**Review by amyjko — APPROVED** [review]
All strings complete! Awesome work, this is a wonderful milestone.

I might remove the es-tutorial, since it's not translated, and I don't want it to look like it is.

**Comment by cmdharo** [comment]
> All strings complete! Awesome work, this is a wonderful milestone.
> 
> I might remove the es-tutorial, since it's not translated, and I don't want it to look like it is.

Yay, it isn't perfect, but it should do! Regarding the tutorial, I and the others have been working on it, but unfortunately, I don't think it's anything substantial—at least for the beta release.

**Comment by amyjko** [comment]
No problem if I delete it from main then? These live in another branch?

**Comment by cmdharo** [comment]
Yes, that's fine! I'll let everyone on the Spanish locale team know.

**Pull request merged**
