### PR TITLE
issue #317 Tested Chinese UI

### PR DESCRIPTION
**Pull request by awang040403**
# Context

Testing and viewing whether all of the Chinese characters is rendered and formatted properly in a readable ways.

## Related issues

None.

## Verification

I took some time to set up the work space and learned methods to update codes for Chinese UI. Then, I tested every page of the Wordplay website multiple times with Chinese UI in Chrome and Safari, including login, projects, galleries, learn, and guide, which are all rendered properly. I also updated some places that have incorrect translation, and now the issue is solved. One thing to mention is that for Chinese UI specifically, it sometimes takes a little longer to render to Chinese in Safari (Eg. It takes a little longer to load Chinese localization and sometimes you are not able to edit codes in Chinese UI). After refreshing the page, the issue is usually fixed. This issue does not happen for Google Chrome, nor it happens when using English UI in Safari. I thought for some time whether I could fix this and also asked in discord help and feedback. I will create an issue about it in Github. I also updated some incorrect translation.

## Checklist

This Chinese UI is fully tested and the issue is resolved.

### CODE REVIEW

**Comment by amyjko** [comment]
@awang040403 I'm unclear on the status of this PR. Is it ready for review and merging? When you submit a PR, please make clear what your request is by fully filling out the PR template and explicitly requesting review.

**Comment by awang040403** [comment]
@amyjko Yes, it is ready to review, but it is not merging. I will take a closer look at the PR template and find out where I did not follow.

**Comment by amyjko** [comment]
Just a few notes on this:

* It looks like there's just a 1 line change in the Chinese locale. Is that the only change you intended? The one change looks good to me, so if that's all you intended, I will approve.
* The PR template is the first post at the top; it looks like you skipped it, which Is why I was asking about the context for the issue.
* To clarify the process, I merge after approving. You don't merge; that requires my approval.

**Comment by awang040403** [comment]
Hi @amyjko, sorry that I forgot to change to the correct formot to show my filled pull request. I have updated it now.

**Review by amyjko — APPROVED** [review]
This locale text fix is acceptable (as far as I can tell with Google Translate :)

**Comment by amyjko** [comment]
Thank you @awang040403, this PR is much clearer now. Please submit those issues — any bugs you find must be reported before we can fix them. (Otherwise we don't know they exist!).

**Pull request merged**
