### PR TITLE
Issue # 384 Modified inaccurate Chinese translations in the Chinese version of the tutorial

### LINKED ISSUE #384: Translation in the simplified Chinese instruction is not native or fluent enough.
## Expected behavior

Some translated phrases in the simplified Chinese tutorial are not contextually aware or native, which may be difficult for those who only speak Chinese to comprehend. 

## Actual behavior

1. Go to the simplified Chinese tutorial
2. Read every sentence from beginning
3. Find sentences that are not translated fluently or natively in Chinese. For example, in line 47, "我还是拉丁字符/f/的小写", the sequence of the adjectives and nouns is in reverse order, and the right sequence should be "我还是小写的拉丁字符/f/".

## Screenshots

N/A

## Environment

It's in the simplified Chinese branch

### PR DESCRIPTION
**Pull request by twu29**
# Context

I modified all the inaccurate and non-native Chinese translations in the Chinese version of the tutorial (from line 1 to line 5378). I will continue to modify rest of the Chinese version of the tutorial after this PR.

## Related issues

-   Related Issue #384 
-   Closes #384

### CODE REVIEW

**Comment by twu29** [comment]
@amyjko Hi Amy, I tried to resolve the previous conflict issues and believe everything is addressed since no further conflict warnings are appearing. Could you please review this PR when you get a chance? Let me know if there’s anything else I need to adjust. Thanks :)

**Comment by amyjko** [comment]
The translations look good, but this PR should not include a modification to the pull request template file. That is the template that anyone creating a pull request will see and then fill out, not where you fill out the details this specific PR. Revert those changes so that you're only changing the tutorial file and then this PR will be ready to mege.

**Comment by twu29** [comment]
@amyjko Hi Amy! After a lot of hard work, I have now successfully reviewed and improved the entire Chinese version of the tutorial, and also modified the previous pull request template file. Can you take another look at my PR? Thanks :)

**Review by amyjko — CHANGES_REQUESTED** [review]
Amazing! Since I cannot read Chinese, I have to rely on others to detect issues with this.

The one thing you do need to resolve is the conflicts between this and the existing Chinese tutorial. Conflicts happen when you and someone else edit something and they cannot be merged together. You'll need to review the conflict, decide whose change to keep, and then commit the manually merged text. You should be able to see who made the edits, in case you need to talk to them to decide what to keep.

**Comment by twu29** [comment]
> Amazing! Since I cannot read Chinese, I have to rely on others to detect issues with this.
> 
> The one thing you do need to resolve is the conflicts between this and the existing Chinese tutorial. Conflicts happen when you and someone else edit something and they cannot be merged together. You'll need to review the conflict, decide whose change to keep, and then commit the manually merged text. You should be able to see who made the edits, in case you need to talk to them to decide what to keep.

The conflict has been resolved, please see my new PR #618.

**Pull request closed without merging**
