### PR TITLE
Create hi-IN-tutorial.json

### PR DESCRIPTION
**Pull request by adhimanjagota**
# Context

We have completed the hindi localization of the tutorial!

[hi-IN-tutorial.json](https://github.com/user-attachments/files/18076327/hi-IN-tutorial.json)

-   Related Issue #
-   Closes #

### CODE REVIEW

**Review by amyjko — CHANGES_REQUESTED** [review]
This pull request is empty; it only includes a Hindi tutorial file, but the file is empty. Please ensure you have committed your local work to your local branch, so it is included in your pull request.

**Comment by adhimanjagota** [comment]
I'm so sorry for this, can you see it now?

**Review by amyjko — CHANGES_REQUESTED** [review]
Since I don't know Hindi, I can't review the quality of the tutorial localization, and will approve assuming it's better than nothing.

One clarification, however, mostly about process: this PR did not come with a complete description, so I don't not know which issue it is closing, and cannot judge whether the issue is complete. Is this #140, and if so, is in intended to also include the translation of the user interface strings? I only see a tutorial, not the rest of the locale, and the comments in the issue are vague. Please clarify.

**Comment by adhimanjagota** [comment]
yes, this is #140 . We are done with the localization of just the tutorial and are planning to continue the rest of the work next quarter.

**Review by amyjko — APPROVED** [review]
Approving initial draft of Hindi tutorial.

**Pull request merged**
