### PR TITLE
333 resolve order of operations conflict

### PR DESCRIPTION
**Pull request by wena04**

### CODE REVIEW

**Comment by amyjko** [comment]
@wena04 Can you provide context for this PR? It needs a description that at a minimum describes the status of what you're requesting (design review, guidance, feedback). What do you need? Remember, you always want to explicitly communicate. Open source projects rely on communication to work well.

**Comment by amyjko** [comment]
@wena04 Are you asking for feedback on this yet? Please communicate when you push updates to a PR.

**Comment by wena04** [comment]
> @wena04 Are you asking for feedback on this yet? Please communicate what you're asking for when you push updates to a PR.

I think I accidentally clicked something to pull when I wasn't trying to. Now I'm not sure how to undo what I did...

**Comment by amyjko** [comment]
@wena04. Okay. Be careful what you click; you want to know what you're doing before you submit things. (Developer tools have so many poorly explained features, it's easy to do unintentional things).

As a guideline, only submit a pull request (PR) when you're asking for feedback or ready to merge. Otherwise, just work in your feature branch. PRs are for when you need my feedback and want to merge your work into production.

**Pull request closed without merging**
