### PR TITLE
Korean locale

### PR DESCRIPTION
**Pull request by anhourandaquarter**
Updating the Korean-locale branch so that we can continue work on it.

### CODE REVIEW

**Review by amyjko — CHANGES_REQUESTED** [review]
This commit should only have the `json` file, but it also has a submodule added, as well as a `www.wordplays.com` file. Please remove those unrelated files from the PR and then I can merge this in.

**Comment by anhourandaquarter** [comment]
I deleted the `www.wordplays.com` file, but I'm not sure how to remove the submodule. Can I follow the steps at this link?

https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule/36593218#36593218

**Comment by amyjko** [comment]
I haven't used submodules, so I'm not 100% certain, but the most recent and relevant answer in that SO post seems to be this one:

```
git rm -r the_submodule
rm -rf .git/modules/the_submodule
```

That would recursively remove the wordplay repo you cloned inside the wordplay repo, and the record of it in the Git folder.

**Comment by anhourandaquarter** [comment]
OK, I followed the instructions there and removed the submodule! It should just be the json now. : )

**Review by amyjko — APPROVED** [review]
Yay, I'm glad to see this making progress!

**Pull request merged**
