### PR TITLE
Chinese-simplified

### PR DESCRIPTION
**Pull request by benjaminmeow**
Updated with feedback given. Tested locally and fixed visible syntax errors.

### CODE REVIEW

**Review by amyjko — CHANGES_REQUESTED** [review]
This PR includes a new dependency, `node-fetch`, and a corresponding change to `package-lock.json`. These shouldn't be included; not only are they not needed for the project, they're not needed for this PR. Thanks!

**Review by benjaminmeow — COMMENTED** [review]
I think I must have added node-fetch when I was trying to debug my npm run dev. I thought I was missing a dependency somehow. Should be fixed now. Thanks!

**Review by amyjko — CHANGES_REQUESTED** [review]
There's still a package-lock.json change in there too. Please remove that, otherwise everyone's npm dependencies will be wrong.

**Comment by benjaminmeow** [comment]
I removed all the node-fetch dependencies that I could find in package-lock.json. Hopefully I did it properly this time?

**Review by amyjko — CHANGES_REQUESTED** [review]
This PR still has revisions to `package-lock.json` and `package.json`. Neither should be changed. Please remove them from the PR and then I will merge.

Additionally, there is a change to `en-US.json` that converts the English into Chinese. Please revert that change.

There is also an incorrectly named tutorial file: it was renamed in this PR to `zh_CN-tutorial.json`, but the tutorial file names use dashes, not underscores. Please revert that change.

**Comment by Davidxuwuhu** [comment]
Is anyone still working on this? I can finish this up.

**Comment by amyjko** [comment]
No one is assigned, so it's all yours. It'd be great to finish this locale!

**Pull request closed without merging**
